version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql/data 
  api:
    build: 
      dockerfile: Dockerfile
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '5000:5000'
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
volumes:
  addressbook-db:
  